server:
  port: 8088


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/auth
    username: postgres
    password: 7432


auth:
  cookie:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN
    secret: hfghfghghsfgsggfsdgfjghjj
    expiration-auth: 600000
    expiration-refresh: 31536000
    path: /
debug: false
